### PR TITLE
Next release

### PR DESCRIPTION
**Pull request by ndelangen**
This is the next release of the chromatic action

This upgrades to the latest chromatic-cli package & adds support for the "preserve-missing" option

### CODE REVIEW

**Comment by ndelangen** [comment]
@tmeasday Do you think I can release this as v1? There are no breaking public facing changes.

But it does contain the major version bump of the chromatic-cli package.

If we choose to release this as v2, there's a high chance users won't get this update/improvement for months, since upgrading to new action releases is manual, and there's no update notifier from github AFAIK.

Personally I'm really tempted to just release this as v1, but I understand if you just want to be on the safe side, and tell users to upgrade when support requests come up.

**Comment by ndelangen** [comment]
testing here:
https://github.com/chromaui/storybook-composition/pull/1/commits/44972ba140501e01c8b697c4ccd1e2456a210062

**Comment by tmeasday** [comment]
Did you check in `node_modules` by accident?

**Comment by tmeasday** [comment]
@ghengeveld I'm not sure if there were any known breaking changes in v5 in the end, do you recall?

**Comment by tmeasday** [comment]
I'm OK with releasing as v1 if not.

**Comment by ghengeveld** [comment]
The --only flag was changed, so technical that's a breaking change. Not really a big deal though because nobody will be using it. Also jsdom was removed but shouldn't be noticeable.

**Comment by ghengeveld** [comment]
So let's ship as action v1.

**Comment by ndelangen** [comment]
I'm going to proceed and release as v1

**Comment by ndelangen** [comment]
> Did you check in node_modules by accident?

No this is by design, we can't use the user's installed chromatic0cli version, because it could be incompatible, and they might not have 1 at all. We also don't want to install dependencies for the action, because that wastes about 17 seconds of time running the action. The fastest way to get an action to run, is if it has everything it needs checked in.

**Pull request merged**
