### PR TITLE
Update action.yml with current inputs

### LINKED ISSUE #25: Update action.yml with current inputs
It looks like some inputs are missing from `action.yml` causing unnecessary build warnings. I'll open a PR that fixes the ones that I'm seeing, but I'll leave it up to the repository maintainers to keep this file up-to-date.

image

### PR DESCRIPTION
**Pull request by Kjens93**
Fixes #25

### CODE REVIEW

**Comment by isaac-martin** [comment]
Can we get a release cut with this shortly?

**Comment by ndelangen** [comment]
I'll do it today!

**Comment by isaac-martin** [comment]
thankyou!

**Comment by ndelangen** [comment]
done!

**Pull request merged**
